# Generated by Django 3.0.2 on 2020-01-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricechecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
