# Generated by Django 3.0.2 on 2020-06-25 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricechecker', '0002_auto_20200128_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='requested_price',
            new_name='highest_requested_price',
        ),
        migrations.AddField(
            model_name='item',
            name='lowest_requested_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.CharField(blank=True, choices=[('JM', 'Jumia'), ('KO', 'Konga')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
