# Generated by Django 3.0.2 on 2020-06-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricechecker', '0003_auto_20200625_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='highest_requested_price',
            new_name='requested_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lowest_requested_price',
        ),
    ]
