# Generated by Django 3.0.2 on 2020-06-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricechecker', '0004_auto_20200625_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
