# Generated by Django 3.0.2 on 2020-07-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricechecker', '0005_auto_20200629_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, help_text='Item Name', max_length=200, null=True),
        ),
    ]
