# Generated by Django 3.0.2 on 2020-07-25 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricechecker', '0006_auto_20200725_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.CharField(blank=True, help_text='If the last price meets the condition of the requested price, the new price is stored here', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_price',
            field=models.CharField(blank=True, help_text='The price that the scraper got last', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user that created the item', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='requested_price',
            field=models.IntegerField(default=0, help_text='The price you want to track (Desired price)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.CharField(blank=True, choices=[('JM', 'Jumia'), ('KO', 'Konga')], help_text='Store choice', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, help_text='Link to the item', max_length=600, null=True),
        ),
    ]
